apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-ds
spec:
  selector:
    matchLabels:
      app: ds-app
  template:
    metadata:
      labels:
        app: ds-app
    spec:
      containers:
      - name: nginx
        image: redis 
