apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: myapp
    version: blue   # 🔥 initially blue
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

